name: nodejs14_express
description: App Description
ignoreFiles: .git node_modules
modules:
- name: typescript
  language: nodejs14.x
  web: express.typescript
  description: Module description
  functions:
  - name: func
    entry: entry.ts
    description: the entry point for the function